### PR TITLE
Bugfix string offsets

### LINKED ISSUE #1: Artist and copyright offsets mixed up
Hi! 

Thanks for a great program in well-written C.

In the `struct` the offsets are the same as the ones in the [spec](https://www.nesdev.org/wiki/NSF#Header_Overview).

```c
char		name[32];		/* offset 0x0e */
char		artist[32];		/* offset 0x2e */
char		copyright[32];		/* offset 0x4e */
```

However the actual code swaps the offsets for artist and copyright.

### PR DESCRIPTION
**Pull request by ullenius**
Fixes #1 

I don't run NetBSD so I can't confirm it compiles there. However it does compile on my Linux machine (GCC 10.2.1) after removing the SHA and MD5sum hash-imports.

Please note that the checksums in the output examples in the doc may need updating.

### CODE REVIEW

**Comment by koitsu** [comment]
Nice catch!  It's been a while since I wrote this, and I remember at the time thinking "Hmm, do I have these 2 fields correct?" but not digging in too closely.

I'll work separately on getting this to compile cleanly on Linux, as I now have several Linux machines in addition to FreeBSD.

**Comment by koitsu** [comment]
P.S. Your PR pulled in a `test` binary into the repository.  I've removed it in 1d49a617c14896fd619cf5fefd6ee0c537d5b08d, but this results in the Git repository having 16KB (the binary) in the index that will forever be tracked.  In the future please pay close attention to `git status` output before doing `git commit`.

**Comment by ullenius** [comment]
@koitsu
Ooops sorry about the binary. Even though I've used git for years I managed to pull of a schoolboy error :disappointed:

`test` is an elf-binary (`gcc -Wall -Werror nsftag.c -o test`), a left-over from another branch. Please consider a rebase of my commit if you deem it necessary.


PS: Thanks for the Linux port

**Comment by koitsu** [comment]
Give the latest master branch a try.  Commit https://github.com/koitsu/nsfinfo/commit/a2d8c34d6ac965fd494ac99880de9a543ac74a60 should work (tested on Ubuntu 22.04.2 LTS jammy with gcc 11.3.0).

**Comment by ullenius** [comment]
Thanks! It works like charm. Tested on Debian bullseye (`gcc 10.2.1`)

**Pull request merged**
